name: CloudStream Derleyici

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.py"

jobs:
  CloudStreamDerleyici:
    runs-on: ubuntu-latest
    steps:
      - name: "'src' Depo Kontrolü"
        uses: actions/checkout@v4.2.2
        with:
          path: "src"

      - name: "'build' Depo Kontrolü"
        uses: actions/checkout@v4.2.2
        with:
          ref: "builds"
          path: "builds"

      - name: Eski Derlemeleri Temizle (GolgeTV.cs3 hariç)
        run: find $GITHUB_WORKSPACE/builds -name '*.cs3' ! -name 'GolgeTV.cs3' -delete

      - name: JDK 17 Ayarla
        uses: actions/setup-java@v4.6.0
        with:
          distribution: adopt
          java-version: 17

      - name: Android SDK Ayarla
        uses: android-actions/setup-android@v3.2.2

      - name: Eklentileri Derle
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: jq Araçlarını Kur (GolgeTV eklemesi için)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: GolgeTV Eklentisini plugins.json'a Elle Ekle
        run: |
          cd $GITHUB_WORKSPACE/builds
          if ! jq -e '.[] | select(.internalName == "GolgeTV")' plugins.json > /dev/null; then
            jq '. += [{
              "iconUrl": "https://www.apkdelisi.net/wp-content/uploads/2022/03/golge-tv-reklamsiz-mod-apk-canli-tv-apkdelisi-0.jpg",
              "apiVersion": 1,
              "repositoryUrl": "https://github.com/nikyokki/nik-cloudstream",
              "fileSize": '"$(stat -c%s GolgeTV.cs3)"',
              "status": 1,
              "language": "tr",
              "authors": ["nikyokki"],
              "tvTypes": ["TV"],
              "version": 1,
              "internalName": "GolgeTV",
              "description": "GolgeTV canlı TV ve diziler için hızlı ve stabil bir çözümdür.",
              "url": "https://raw.githubusercontent.com/nikyokki/nik-cloudstream/builds/GolgeTV.cs3",
              "name": "GolgeTV"
            }]' plugins.json > plugins-new.json && mv plugins-new.json plugins.json
          else
            echo "GolgeTV zaten plugins.json'da mevcut, eklenmedi."
          fi

      - name: Derlemeleri Yükle
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "$GITHUB_SHA 'nın Derlenmesi" || exit 0
          git push --force
